### ISSUE TITLE
DSCAN的问题

### ISSUE THREAD

**Issue by hhhhhon** [PyxYuYu/MyBlog#109]
运用sqlmapapi出现问题
Traceback (most recent call last):
  File "C:\Python27\sqlmap\thirdparty\bottle\bottle.py", line 935, in _inner_handle
    return route.call(**args)
  File "C:\Python27\sqlmap\thirdparty\bottle\bottle.py", line 1888, in wrapper
    rv = callback(*a, **ka)
  File "C:\Python27\sqlmap\lib\utils\api.py", line 483, in scan_start
    DataStore.tasks[taskid].engine_start()
  File "C:\Python27\sqlmap\lib\utils\api.py", line 175, in engine_start
    self.process = Popen(["sqlmap", "--api", "-c", configFile], shell=False, close_fds=not IS_WIN)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2]
是什么问题啊

**Comment by PyxYuYu** [comment]
@hhhhhon WindowsError: [Error 2]，查了下是系统找不到指定文件，看看是否有什么缺失，或者下个新版的 Sqlmap 试试看

**Comment by hhhhhon** [comment]
@PyxYuYu 我的sqlmap和python都是新下的     请问您的path路径里是单独配置sqlmap.py的路径还是直接配置python的路径

**Comment by PyxYuYu** [comment]
我没有配置路径啊，先在 cmd 下运行 Sqlmapapi.py，它会在 http://127.0.0.1:8775 运行，/sqliscan
<https://github.com/PyxYuYu/MyBlog/tree/master/DjangoProject-DSScan/DSScan/sqliscan>
/*sqls.py 中直接调用这个 API*

2017-05-08 22:34 GMT+08:00 hhhhhon <notifications@github.com>:

**Comment by OldFatBoy** [comment]
大神，请教一下这个在linux下怎么运行？

**Comment by PyxYuYu** [comment]
@OldFatBoy 编码问题，试试简单点的英文路径，我是直接放在根目录下的所以没遇过这些问题
